# Generated by Django 5.2.6 on 2025-09-22 11:02

import home.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usertable',
            managers=[
                ('objects', home.models.UserTableManager()),
            ],
        ),
    ]
