# Generated by Django 5.2.6 on 2025-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('working', 'Working'), ('holding', 'Holding')], default='working', max_length=20),
        ),
    ]
